package org.integrallis.drools.oopath

rule "Lives in Arizona"
when
    person: Person( /address[ state == "AZ" ] )
then
    System.out.println("Arizona: " + person.getName() + " lives at " + person.getAddress());
end

rule "Recommend Business"
when
    person: Person( $state: /address/state )
    company: Company( /locations[ state == $state ] )
then
    System.out.println("Recommend: " + company.getName() + " to " + person.getName());
end

